version: '{build}'
skip_tags: true
image: Visual Studio 2022
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
before_build:
- cmd: before_build.bat
build:
  project: build/WidescreenFixesPack.sln
  parallel: true
  verbosity: minimal
before_package:
- cmd: >-
    before_packaging.bat

    cd data

    release.bat
after_build:
- ps: Get-ChildItem .\Archives\*.zip  | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }