trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - .appveyor.yml

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - .appveyor.yml

jobs:
- job:
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      Release:
        configuration: Release
      Debug:
        configuration: Debug

  steps:
  - task: CmdLine@2
    displayName: Before build
    inputs:
      script: |
        git submodule update --init --recursive
        premake5.exe vs2022
        ./before_build.bat

  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      maximumCpuCount: true
