name: "Build All"

inputs:
  project:
    description: "Project name"
    required: false

runs:
  using: "composite"
  steps:
  - name: Add msbuild to PATH
    uses: microsoft/setup-msbuild@v1.3.2
  - name: Configure build
    shell: cmd
    run: |
      ./premake5.bat
  - name: Before Build
    shell: cmd
    run: |
      ./before_build.bat
  - name: Build
    shell: cmd
    run: |
      msbuild -m build/WidescreenFixesPack.sln ${{inputs.project}} /property:Configuration=Release
  - name: Before Package
    shell: cmd
    run: |
      ./before_packaging.bat
  - name: Pack binaries
    shell: cmd
    run: |
      cd ./data
      release.bat
  - name: Upload artifacts to actions
    uses: actions/upload-artifact@v4
    with:
      name: WidescreenFixesPack
      path: ./data/Archives/*.zip
